version: 0.2

phases:
  pre_build:
    commands:
      - echo running doekcer-compose ... | tee -a log.txt
      - docker-compose up -d
  build:
    commands:
      - echo running test ... | tee -a log.txt
      - docker-compose exec -T mono ./test.sh 
  post_build:
    commands:
      - docker-compose down
